<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Stock Alert Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            text-align: center;
        }
        .summary {
            background-color: #e8f5e8;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #4caf50;
        }
        .alert-summary {
            background-color: #fff3e0;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #ff9800;
        }
        .attachment-info {
            background-color: #e3f2fd;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #2196f3;
        }
        .no-items {
            text-align: center;
            color: #666;
            font-style: italic;
            padding: 20px;
            background-color: #e8f5e8;
            border-radius: 5px;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 14px;
        }
        .highlight {
            background-color: #fff3e0;
            padding: 2px 6px;
            border-radius: 3px;
            font-weight: bold;
        }
        .low-stock {
            color: #ff9800;
            font-weight: bold;
        }
        .out-of-stock {
            color: #d32f2f;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Daily Stock Alert Report</h1>
        <p><strong>Report Date:</strong> {{ $reportDate }}</p>
        <p><strong>Generated At:</strong> {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
    <div class="attachment-info">
        <h2>📎 Excel Report Attached</h2>
        <p><strong>Attachment:</strong> {{ $excelFileName }}</p>
        <p>The complete inventory alert report with all low stock and out of stock items is available in the attached Excel file.</p>
        <p><strong>Excel Features:</strong></p>
        <ul>
            <li>Complete item details with current stock levels and reorder points</li>
            <li>Separate sections for low stock and out of stock items</li>
            <li>Color-coded status indicators for easy identification</li>
            <li>Sortable and filterable data for inventory analysis</li>
            <li>Rate information for cost calculations</li>
        </ul>
    </div>

    <div class="footer">
        <p><strong>Inventory Management Guidelines:</strong></p>
        <p><strong>Low Stock:</strong> Items below reorder level but still available</p>
        <p><strong>Out of Stock:</strong> Items with zero inventory requiring immediate attention</p>
        <p><strong>Note:</strong> This report is generated daily to help maintain optimal inventory levels.</p>
        <p>This is an automated report generated by the Smart Belt Inventory Management System.</p>
        <p>Report generated on {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>