<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smart Stock Alert Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            text-align: center;
        }
        .summary {
            background-color: #e8f5e8;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #4caf50;
        }
        .dies-summary {
            background-color: #fff3e0;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #ff9800;
        }
        .attachment-info {
            background-color: #e3f2fd;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #2196f3;
        }
        .no-items {
            text-align: center;
            color: #666;
            font-style: italic;
            padding: 20px;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 14px;
        }
        .highlight {
            background-color: #fff3e0;
            padding: 2px 6px;
            border-radius: 3px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🏭 Smart Stock Alert Report</h1>
        <h2>Dies Required for Production</h2>
        <p><strong>Report Date:</strong> {{ now()->format('Y-m-d') }}</p>
        <p><strong>Generated At:</strong> {{ $alertData['generated_at'] ?? now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <div class="summary">
        <h2>📊 Alert Summary</h2>
        <p><strong>Total Items Needing Attention:</strong> {{ $alertData['total_items'] ?? 0 }}</p>
        <p><strong>Belt Types Affected:</strong> {{ count($alertData['belt_types'] ?? []) }}</p>
    </div>

    <div class="dies-summary">
        <h2>🔧 Dies Required Summary</h2>
        <p><strong>Total Dies Needed:</strong> <span class="highlight">{{ $alertData['total_dies_needed'] ?? 0 }} dies</span></p>
        <p><em>This represents the minimum number of dies required to bring all low-stock items back to their reorder levels.</em></p>
    </div>

    <div class="attachment-info">
        <h2>📎 Excel Report Attached</h2>
        <p><strong>Attachment:</strong> {{ $excelFileName }}</p>
        <p>The detailed breakdown with all low-stock items, die calculations, and production planning summary is available in the attached Excel file.</p>
        <p><strong>Excel Features:</strong></p>
        <ul>
            <li>Complete item details with stock levels and die requirements</li>
            <li>Formatted tables with color-coded status indicators</li>
            <li>Production planning summary by belt type</li>
            <li>Sortable and filterable data for easy analysis</li>
        </ul>
    </div>

    @if(empty($alertData['belt_types']))
        <div class="no-items">
            <h3>🎉 Excellent News!</h3>
            <p>No items currently require die production alerts.</p>
            <p>All tracked inventory levels are above their reorder points or have already been alerted.</p>
        </div>
    @else
        <div style="background-color: #e3f2fd; padding: 15px; border-radius: 5px; margin-top: 20px;">
            <h3>📋 Quick Overview</h3>
            @foreach($alertData['belt_types'] as $beltType => $beltData)
                <p><strong>{{ $beltData['name'] }}:</strong> {{ $beltData['total_dies'] }} dies needed across {{ count($beltData['sections']) }} sections ({{ $beltData['total_items'] }} items)</p>
            @endforeach
        </div>
    @endif

    <div class="footer">
        <p><strong>How Dies are Calculated:</strong></p>
        <p>Dies Needed = CEIL((Reorder Level - Current Stock) / Stock per Die)</p>
        <p><strong>Note:</strong> This report only includes items that haven't been alerted yet and are below their reorder levels.</p>
        <p><strong>Smart Alerts:</strong> Once an alert is sent for an item, it won't appear again until stock is replenished above the reorder level.</p>
        <p>This is an automated report generated by the Smart Belt Inventory Management System.</p>
        <p>Report generated on {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>