<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smart Stock Alert Report - Dies Required</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            text-align: center;
        }
        .summary {
            background-color: #e8f5e8;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #4caf50;
        }
        .dies-summary {
            background-color: #fff3e0;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #ff9800;
        }
        .belt-section {
            margin-bottom: 30px;
            border: 1px solid #ddd;
            border-radius: 8px;
            overflow: hidden;
        }
        .belt-header {
            background-color: #2196f3;
            color: white;
            padding: 15px;
            font-weight: bold;
            font-size: 18px;
        }
        .section-header {
            background-color: #f5f5f5;
            padding: 10px 15px;
            font-weight: bold;
            border-bottom: 1px solid #ddd;
        }
        .belt-content {
            padding: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            padding: 8px 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }
        .dies-needed {
            color: #ff5722;
            font-weight: bold;
            font-size: 16px;
        }
        .stock-level {
            color: #d32f2f;
            font-weight: bold;
        }
        .no-items {
            text-align: center;
            color: #666;
            font-style: italic;
            padding: 20px;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 14px;
        }
        .highlight {
            background-color: #fff3e0;
            padding: 2px 6px;
            border-radius: 3px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Smart Stock Alert Report</h1>
        <p><strong>Report Date:</strong> {{ $reportDate }}</p>
        <p><strong>Generated At:</strong> {{ $alertData['generated_at'] ?? now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <div class="footer">
        <p><strong>How Dies are Calculated:</strong></p>
        <p>Dies Needed = CEIL((Reorder Level - Current Stock) / Stock per Die)</p>
        <p><strong>Note:</strong> This report only includes items that haven't been alerted yet and are below their reorder levels.</p>
        <p><strong>Smart Alerts:</strong> Once an alert is sent for an item, it won't appear again until stock is replenished above the reorder level.</p>
        <p>This is an automated report generated by the Smart Belt Inventory Management System.</p>
        <p>Report generated on {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>